USE [CharacterGen]
GO
IF EXISTS (Select * from sys.procedures WHERE name = 'InsertSpells')
	Drop procedure InsertSpells
GO

Create Procedure InsertSpells
as
Begin
	Delete From Spells Where Spell_Id > -1;
	DBCC CHECKIDENT (Spells, RESEED, 0);
  --insert into Weapons values ('Name, DC, CastTime, Duration, Components, Range, Target, AreaOfEffect, Damage)   
   
	insert into Spells values ('Acid Splash', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Aid', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Alter Self', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Animal Friendship', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Animal Messenger', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Animal Shapes', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Animate Dead', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Animate Objects', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Antilife Shell', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Antimagic Field', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Antipathy/Sympathy', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Arcane Eye', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Arcane Lock', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Armor of Agathys', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Arms of Hadar', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Astral Projection', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Augury', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Aura of Life', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Aura of Purity', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Aura of Vitality', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Awaken', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	
	insert into Spells values ('Bane', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Banishing Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Banishment', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Barkskin', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Beacon of Hope', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Beast Sense', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Bestow Curse', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Bigby''s Hand', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blade Barrier', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blade Ward', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Bless', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blight', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blinding Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blindness/Deafness', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blink', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Blur', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Branding Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Burning Hands', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	
	insert into Spells values ('Call Lightning', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Calm Emotions', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Chain Lightning', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Charm Person', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Chill Touch', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Chromatic Orb', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Circle of Death', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Circle of Power', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Clairvoyance', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Clone', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Cloudkill', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Cloud of Daggers', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Color Spray', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Command', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Commune', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Commune with Nature', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Compelled Duel', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Comprehend Languages', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Compulsion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Cone of Cold', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Confusion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Animals', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');	
	insert into Spells values ('Conjure Barrage', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Celestial', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Elemental', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Fey', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Minor Elementals', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Volley', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Conjure Woodland Beings', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Contact Other Plane', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Contagion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Contingency', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Continual Flame', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Control Water', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Control Weather', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Cordon of Arrows', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Counterspell', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Create Food and Water', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Create or Destory Water', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Create Undead', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Creation', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Crown of Madness', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Crusader''s Mantle', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Cure Wounds', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Dancing Lights', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Darkness', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Darkvision', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Daylight', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Death Ward', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Delayed Blast Fireball', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Demiplane', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Destructive Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Detect Evil and Good', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Detect Magic', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Detect Poison and Disease', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Detect Thoughts', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dimension Door', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Disentegrate', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Disguise Self', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dispel Evil and Good', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dispel Magic', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dissonant Whispers', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Divination', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Divine Favor', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Divine Word', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Druidcraft', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dominate Beast', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dominate Monster', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dominate Person', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Dream', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Drawmi''s Instant Summons', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Earthquake', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Eldritch Blast', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Elemental Weapon', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Enhance Ability', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Enlarge/Reduce', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Ensnaring Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Entangle', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Enthrall', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Etheralness', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Evard''s Black Tentacles', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Expeditious Retreat', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Eyebite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Fabricate', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('False Life', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Faerie Fire', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Feather Fall', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fear', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Feeblemind', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Feign Death', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage')
	insert into Spells values ('Find Familiar', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Find Steed', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');;
	insert into Spells values ('Find the Path', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Find Traps', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Finger of Death', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fire Bolt', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fire Shield', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fire Storm', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fireball', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Flame Blade', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Flame Strike', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Flaming Sphere', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Flesh to Stone', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fly', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Fog Cloud', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Forbiddance', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Forcecage', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Foresight', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Freedom of Movement', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Friends', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	
	insert into Spells values ('Gate', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Gaseous Form', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Geas', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Gentle Repose', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Giant Insect', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Gilbness', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Globe of Invulnerability', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Grasping Vine', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Grease', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Greater Invisibility', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Greater Restoration', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Goodberry', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Guardian of Faith', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Guards and Wards', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Guidance', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Guiding Bolt', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Gust of Wind', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Glyph of Warding', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Hall of Thorns', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hallow', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hallucinatory Terrain', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Harm', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Haste', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Heal', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Healing Word', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hellish Rebuke', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Heros'' Feast', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Heroism', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Heat Metal', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hex', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hold Monster', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hold Person', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Holy Aura', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hunger of Hadar', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hunter''s Mark', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Hypnotic Pattern', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Ice Storm', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Identify', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Illusory Script', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Imprisionment', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Incendiary Cloud', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Inflict Wounds', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Insect Plauge', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Invisibility', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Jump', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Knock', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Light', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Legend Lore', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Leomund''s Secret Chest', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Leomund''s Tiny Hut', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Lesser Restoration', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Levitate', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Lightning Arrow', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Lightning Bolt', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Locate Animals or Plants', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Locate Creature', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Locate Object', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Longstrider', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Mage Armor', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mage Hand', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Magic Circle', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Magic Jar', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Magic Missile', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Magic Mouth', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Magic Weapon', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Major image', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mass Cure Wounds', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mass Heal', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mass Healing Word', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mass Suggestion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Maze', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Meld into Stone', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Melf''s Acid Arrow', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mending', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Meteor Swarm', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Message', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mind Blank', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Minor Illusion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mirrage Arcane', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mirror Image', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mislead', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Misty Step', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Modify Memory', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Moonbeam', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mordenkainen''s Faithful Hound', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mordenkainen''s Magnificent Mansion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mordenkainen''s Private Sanctum', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Mordenkainen''s Sword', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Move Earth', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Nondetection', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Nystul''s Magic Aura', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Otiluke''s Freezing Sphere', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Otiluke''s Resilient Sphere', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Otto''s Irresistible Dance', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Planar Binding', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Plane Shift', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Plant Growth', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Programmed Illusion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Project Image', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Purify Food and Drink', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('See Invisibility', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Silence', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Silent Image', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Shatter', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sleep', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Speak With Animals', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Suggestion', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Pass without Trace', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Passwall', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Phantasmal Force', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Phantasmal Killer', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Phantom Steed', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Planar Ally', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Poison Spray', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Polymorph', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Power Word Heal', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Power Word Kill', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Power Word Stun', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Prayer of Healing', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Prestidigitation', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Prismatic Spray', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Prismatic Wall', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Produce Flame', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Protection from Energy', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Protection From Evil and Good', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Protection from Poison', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	
	insert into Spells values ('Raise Dead', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Rary''s Telephatic Bond', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Ray of Enfeeblement', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Ray of Frost', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Ray of Sickness', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Regenerate', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Reincarnate', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Remove Curse', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Resurrection', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Reverse Gravity', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Revify', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Rope Trick', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	
	insert into Spells values ('Sacred Flame', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sanctuary', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Scorching Ray', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Scrying', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Searing Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Seeming', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sending', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sequester', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Shapechange', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Shield', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Shield of Faith', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Shillelagh', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Shocking Grasp', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Simulacrum', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sleet Storm', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Slow', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Spare the Dying', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Speak with Aniamls', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Speak with Dead', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Speak with Plants', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Spider Climb', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Spike Growth', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sprit Guardian', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Spiritual Weapon', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Stinking Cloud', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Staggering Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Stone Shape', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Stoneskin', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Storm of Vengeance', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sunbeam', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Sunburst', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Swift Quiver', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Symbol', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Tasha''s Hideous Laughter', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Telekenesis', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Teleport', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Teleportation Circle', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Tenser''s Floating Disk', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Thaumaturgy', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Thorn Whip', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Thunderous Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Thunderwave', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Time Stop', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Tongues', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Transport via Plants', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Trap the Soul', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Tree Stride', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('True Polymorph', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('True Resurrection', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('True Seeing', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('True Strike', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Tsunami', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Unseen Servant', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Vampiric Touch', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Viscious Mockery', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	
	insert into Spells values ('Wall of Fire', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wall of Force', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wall of Ice', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wall of Stone', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wall of Thorns', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Warding Bond', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');	
	insert into Spells values ('Water Breathing', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Water Walk', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Web', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Weird', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wind Walk', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wind Wall', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wish', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Witch Bolt', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Word of Recall', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
	insert into Spells values ('Wrathful Smite', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');

	insert into Spells values ('Zone of Truth', 0, 'CastTime', 'Duration', 'Components', 'Range', 'Target', 'AreaOfEffect', 'Damage');
end;